services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/chefselect-backend
    env_file:
      - .env
    depends_on:
      - db
    # command: sh -c "tail -f /dev/null"
    command: >
      sh -c '
        flask db upgrade && 
        python -c "from app import create_app; app=create_app(); app.app_context().push(); from app.auth.seed import seed_dev_user; seed_dev_user()" && 
        flask run --host=0.0.0.0
      '

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chefselect-dev-db
      POSTGRES_USER: chefselect
      POSTGRES_PASSWORD: postgres

  test_db:
    image: postgres:13
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_DB: chefselect-test-db
      POSTGRES_USER: chefselect
      POSTGRES_PASSWORD: postgres
